# 下記の順番がルール
# version: "バージョン値"
# services:
#   コンテナ1:
#   コンテナ2:
#   ...
# networks:
#   ネットワーク名1:
#   ネットワーク名2:
#   ...
# volumes:
#   ボリューム名1:
#   ボリューム名2:
#   ...


# services:
#   mysql:
#     build: ./mysql
#     container_name: mysql
#     env_file:
#       - ./mysql/db.env # MySQL設定ファイル
#     volumes:
#       - ./mysql/data:/var/lib/mysql # 実データの永続化
#       - ./mysql/log:/var/log/mysql # logの永続化
#     ports:
#       - 3306:3306

version: '3.6'
services:
  java:
    container_name: java
    build: ./
    tty: true
    volumes:
      - ./src:/java_project/